### ISSUE TITLE
about the microcode

### ISSUE THREAD

**Issue by carson512** [freecableguy/v3x4#8]
I remove the microcode from the bios.
But the motherboard don‘t allow boot...

So is there a older microcode can do the same? Which verison.

And i used a older microcode.But when the windows10 boot it loaded the 43 verison microcode auto....
how to solve it...

**Comment by freecableguy** [comment]
It is important that you _only_ remove the Haswell-E (v3) microcode revision patch updates in the BIOS. Leave all microcode revision patch updates for Broadwell-E (v4) intact. Make a new BIOS and flash via SPI to replace the faulted BIOS.

Windows 10 is now at microcode revision level 0x43 as of build 1909. Take ownership of and rename "mcupdate_GenuineIntel.dll" found in \Windows\System32 folder to prevent auto-microcode patching in Windows.

Download the VMWare tool: https://labs.vmware.com/flings/vmware-cpu-microcode-update-driver
Download microcode: version 0x27 & 0x39 microcode for Haswell-E (0x306F2) in VMWare driver / Linux compatible format: https://1drv.ms/u/s!Ag6oE4SOsCmDhFnET3uw9wHeV4EA

Install VMWare driver: use 0x27 microcode for best performance; 0x39 driver for "better" stability. Copy the file 0x27.dat (or 0x39) to the same folder as the VMWare utility and rename it to 'microcode.dat'. 

Download and copy these files to the same folder:
'microcode_amd.bin'
'microcode_amd_fam15h.bin'

Execute 'install.bat' as admin and reboot.
Check microcode revision level with HWiNFO.

**Comment by freecableguy** [comment]
Re-opening for visibility.

**Comment by carson512** [comment]
Thanks for the Windows 10 autoload problem sloved.
Now I use the bios with 'cpu306F2_plat6F_ver0000001D_2014-04-15' microcode.
Can't Do the All-core turbo..
So change to  0x27 microcode or must remove the  306F2 microcode?

**Comment by freecableguy** [comment]
_All_ embedded microcode patches for CPUID 306F2 (leave all other microcode as-is) _must_ be removed from the BIOS to be flashed.
Entering UEFI setup there should be no microcode patch loaded (some boards will indicate this in properties listing for CPU).
New microcode to be applied at OS load using VMWare tool.

**Comment by carson512** [comment]
Thanks.Will check for remove microcode.

**Comment by peylight** [comment]
@carson512 Can you contact to me?

**Comment by freecableguy** [comment]
How can I help?

**Comment by carson512** [comment]
recently solved the bios problem.In HWinfo show none uCU.

> Use EFI Shellx64 or other suitable UEFI shell to set automatic load (and execution) of v3x4.efi during system boot. Use cmd ' bcfg driver add 0 fs1:\EFI\Boot\v3x4.efi "V3 Full Turbo" ' where 'fs1:\EFI\Boot\v3x4.efi' 

but use this way seem not funtion.Still x26 ratio...How to check the problem...



so i try add E5-50.ffs to the bios file. the ratio chang to x30 but can't lock.(maybe the TDP?)
system have  two 6 Cores 12 Threads CPUs.So it have 12Cores 24 Threads.
but windows 10 use HWinf or CINEBENCH just found  10Cores 19 Threads.

**Comment by freecableguy** [comment]
Be sure to **Enable** C3 and **Disable** C6 in BIOS.
C6 is borked for Haswell-E... C3 enabled sets the bit to allow for "opportunistic" clock increases.

Recommend CPU Package limit C0/C1 and C1E Enabled.
Check Turbo Boost Enabled in CPU power configuration.

**Comment by ahzay** [comment]
Hi, commenting much later but there has been recent development. There is a russian tool called S3TurboTool which allows for generating a DXE driver along with the SVID/FIVR hack which is added into the bios using UEFITool. The process is detailed here: https://github.com/Koshak1013/HuananzhiX99_BIOS_mods and I've attached a translated screenshot of the tool.

![image](https://user-images.githubusercontent.com/43910262/126192704-ffa0d521-c249-4eef-9a52-697a8e33d7c1.png)

However me and other users on overclockers.ru seem to still be hitting the TDP limitation despite the SVID bug exploit. How can that be? Are you able to maintain all-core turbo for extended amounts of time with your driver? for example my 2x2680V3 only stay at 3.3GHz for about a minute before throttling down to 2.8GHz despite thermals being low. Undervolting seems to make the boost last a little longer but TDP limits are reached nonetheless.

**Comment by freecableguy** [comment]
TDP limits in the form of maximum current/EDP limit (Electrical Design Point) are hard-coded in the processor circuitry for safety reasons and cannot be exceeded by any means.  A CPU is a like an engine (just an air pump to which fuel is added)... it will continue to do more work as you feed more voltage/current for higher frequency/power operation, until it fails (system crash or permanent destruction), hence the limiter so we get the crash and not the house burning down.  Incidentally, this is the same reason the engine in your vehicle likely has a rev limiter.  Yes, if you spin the engine faster it _will_ do more work (assuming you can feed enough air and fuel)... but can you keep it from flying apart?  Every system be it mechanical or electrical has a _mechanical_ limit... there is no such thing as an electrical failure, it's really just a mechanical failure when you get down to it (i.e. traces burn out and open up, gates are vaporized due to heat -- photons, _not_ electrons -- or the whole thing melts, etc.).  BTW, everything is light if you didn't know.  "Mass" is just spun-up light combined in progressively higher "densities".  But I digress...

This driver unlocks all **potential** for _opportunistic_ increases, within allowable safety limits (which, again, cannot be modified as this is set during fabrication by blowing tiny, internal fuses which correspond to the desired set point)... keep in mind overall power consumption is a function of voltage _and_ temperature (as temperature increases so does power consumption)... an inherently unstable positive feedback loop which can lead to thermal runaway if not properly controlled with sufficient cooling.  As the CPU heats and power consumption increases, clocks must be reduced to remain within power limits.

Three options for increasing either maximum overclock or duration (can be indefinite): (1) lower voltage by selecting and loading a higher negative VCORE offset pre-complied .EFI file (or make your own) -- shifts the whole _effective_ voltage/frequency curve _up_, (2) increase FSB (my ASUS dual-socket board is stable up to 110MHz) -- also shifts the whole effective voltage/frequency curve up, unbeknownst to the internal power control unit (PCU), which assumes 100Mhz FSB -- these Xeons were never designed for variation in FSB, and/or (3) provide additional heat rejection (cooling).

With custom water cooling I am able to boost and sustain all-core turbo of approximately 3.55GHz under 100% loads and sometimes up to almost 4GHz under "lighter" 100% loads (there's a difference in power consumption depending on the instruction set utilized, i.e. AVX vs. AVX2 for example).  Seeing as how Haswell-EP can consume up to about 260W (EDP limit), you will need some hefty cooling to keep those clocks up.  Double that if you have a dual-processor system on the same loop.  Coincidently, better cooling will reduce the required minimum operating voltage for a given frequency -- ah ha... a _negative_ feedback loop, just what we want!  If not already clear, **cooling** is key.

Looking at how Zen4 and Zen5 operate these days, it's clear to me that AMD has essentially copied Intel's development here, albeit with some major improvements very similar to current-generation Intel CPUs (as of 2023-2024).  Precision Boost 2, Opportunistic Turbo 3, blah blah blah, all the same... AMD and Intel have simply implemented the same control model provided by this driver and let the EDP limit become the final limit and not some artificially lower setting.  Funny how things work out.

Hope this helps.
